### ISSUE TITLE
你好，请问这份数据里用的词性标注是什么标准的，我在网上找了很久没找到

### ISSUE THREAD

**Issue by onewaymyway** [HIT-SCIR/SemEval-2016#1]
有这份数据用的词性标注标准文档吗

**Comment by Oneplus** [comment]
ctb的词性吧 http://www.cs.brandeis.edu/~clp/ctb/posguide.3rd.ch.pdf

**Comment by onewaymyway** [comment]
> ctb的词性吧 http://www.cs.brandeis.edu/~clp/ctb/posguide.3rd.ch.pdf

确实是，谢了
